(include_subdirs no)

(executable
 (name bench_executor)
 (public_name eon-engine-bench-executor)
 (modules bench_executor)
 (libraries bechamel unix eon-engine benchmark_helpers)
 (flags (:standard -warn-error -a))
 (package eon-engine))

(executable
 (name bench_render_stream)
 (public_name eon-engine-bench-render-stream)
 (modules bench_render_stream)
 (libraries bechamel unix eon-engine benchmark_helpers)
 (flags (:standard -warn-error -a))
 (package eon-engine))

(executable
 (name bench_prefab)
 (public_name eon-engine-bench-prefab)
 (modules bench_prefab)
 (libraries bechamel unix eon-engine benchmark_helpers)
 (flags (:standard -warn-error -a))
 (package eon-engine))
