(library
 (name benchmark_helpers)
 (modules benchmark_helpers)
 (libraries bechamel eon_ecs))

(executable
 (name bench_sparse_set)
 (public_name eon-ecs-bench-sparse-set)
 (modules bench_sparse_set)
 (libraries bechamel unix eon_ecs benchmark_helpers)
 (flags (:standard -warn-error -a))
 (package eon-ecs))
