(library
 (name benchmark_helpers)
 (modules benchmark_helpers)
 (libraries bechamel eon_ecs))

(library
 (name query_bench_defs)
 (modules query_bench_defs)
 (libraries bechamel eon_ecs benchmark_helpers))

(executable
 (name bench_sparse_set)
 (public_name eon-ecs-bench-sparse-set)
 (modules bench_sparse_set)
 (libraries bechamel unix eon_ecs benchmark_helpers)
 (flags (:standard -warn-error -a))
 (package eon-ecs))

(executable
 (name bench_entity_manager)
 (public_name eon-ecs-bench-entity-manager)
 (modules bench_entity_manager)
 (libraries bechamel unix eon_ecs benchmark_helpers)
 (flags (:standard -warn-error -a))
 (package eon-ecs))

(executable
 (name bench_query)
 (public_name eon-ecs-bench-query)
 (modules bench_query)
 (libraries bechamel unix eon_ecs benchmark_helpers query_bench_defs)
 (flags (:standard -warn-error -a))
 (package eon-ecs))

(executable
 (name bench_query_large)
 (public_name eon-ecs-bench-query-large)
 (modules bench_query_large)
 (libraries bechamel unix eon_ecs benchmark_helpers query_bench_defs)
 (flags (:standard -warn-error -a))
 (package eon-ecs))

(executable
 (name bench_world)
 (public_name eon-ecs-bench-world)
 (modules bench_world)
 (libraries bechamel unix eon_ecs benchmark_helpers)
 (flags (:standard -warn-error -a))
 (package eon-ecs))

(executable
 (name bench_loop)
 (public_name eon-ecs-bench-loop)
 (modules bench_loop)
 (libraries bechamel unix eon_ecs benchmark_helpers)
 (flags (:standard -warn-error -a))
 (package eon-ecs))
